#!/bin/bash

## Docker Basic Commands
docker version - Check installed Docker version

docker info - System-wide Docker information

docker help - Help for all Docker commands



## Images Management
docker pull <image> - Download an image from Docker Hub

docker images - List local images

docker rmi <image-id> - Remove an Image

docker build -t <image>:<tag> . - Build a new image from Dockerfile
. represents the location of Dockerfile which is in current directory

docker tag <image> <repo>:<tag> - Tag an image for pushing

docker push <repo>:<tag> - Push an image to registry (dockerhub)


## Containers Lifecycle
docker run <image> - Run a container interactively

docker run -d <image> - Run in detached mode (in background)

docker run -p <host>:<container> - Map ports

docker ps - List running containers

docker ps -a - List all containers (including stopped)

docker stop <container> - Stop a running container

docker start <container> - Start a stopped container

docker restart <container> - Restart container

docker rm <container> - Remove container

docker logs <container> - View container logs

docker exec -it <container> bash - Get interactive shell into running container

docker inspect <container> - View detailed container config

docker update <container> --restart unless-stopped - Set restart policy



## Volumes + Storage

docker volume create <name> - Create volume

docker volume ls - List volumes

docker volume inspect <name> - Volume Details

docker volume rm <name> - Delete Volume

docker volume prune - Remove unused local volumes



## Docker Networks

docker networks ls - List networks

docker network create <name> - Create custom network

docker network inspect <name> - Network details

docker network connect <network> <container> - Attach container to network




## Docker Compose

docker-compose up - Start services from docker-compose.yml

docker-compose down - Stop and remove services

docker-compose ps - Show running services

docker-compose logs - View logs for all services




## System Cleanup

docker system diff - Show disk usage

docker system prune - Remove all unused data

docker container prune - Remove stopped containers

docker image prune - Remove unused images


## Advanced/Debugging

docker stats - Live resource usage (CPU, RAM, network)

docker top <container> - Show running processes inside container

docker history <image> - Show image layer history

docker save/docker load - Export/Import images as tar files

docker export/docker import - Export/Import container filesystems as tar
